name: Build book

on:
  push:
    branches-ignore:
      - gh-pages
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install cargo
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal

      - name: Install mdbook
        run: curl -sSL https://github.com/rust-lang/mdBook/releases/download/v0.4.34/mdbook-v0.4.34-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=$HOME/.cargo/bin

      # Ubuntu 22.04's Pandoc can't handle mdbook-mk.lua, so use latest 2.x release
      # TODO: Debug and make Lua compatible?
      - name: Download Pandoc
        run: wget 'https://github.com/jgm/pandoc/releases/download/2.19.2/pandoc-2.19.2-1-amd64.deb'

      - name: Install packages
        run: sudo apt-get update && sudo apt-get install -y make ./pandoc-2.19.2-1-amd64.deb texlive-latex-extra

      - name: Checkout source
        uses: actions/checkout@v2

      - name: Build book
        run: mdbook build
        
      - name: Build PDF
        run: make

      - name: Upload book artifact
        uses: actions/upload-artifact@v2
        with:
          name: book
          path: book/html

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v2
        with:
          name: book.pdf
          path: book.pdf

  draft-release:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download book artifact
        uses: actions/download-artifact@v2
        with:
          name: book
          path: morello-early-performance-results-snapshot-${{ github.sha }}

      - name: Download PDF artifact
        uses: actions/download-artifact@v2
        with:
          name: book.pdf
          path: morello-early-performance-results-snapshot-${{ github.sha }}.pdf

      - name: Create archive
        run: zip -r morello-early-performance-results-snapshot-${{ github.sha }}.zip morello-early-performance-results-snapshot-${{ github.sha }}

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date -u +'%Y%m%d')"

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: draft-${{ steps.date.outputs.date }}-${{ github.sha }}
          release_name: Draft release ${{ steps.date.outputs.date }}
          body: Latest snapshot (${{ github.sha }})
          prerelease: true

      - name: Upload release book asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: morello-early-performance-results-snapshot-${{ github.sha }}.zip
          asset_name: morello-early-performance-results-snapshot-${{ github.sha }}.zip
          asset_content_type: application/zip

      - name: Upload release PDF asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: morello-early-performance-results-snapshot-${{ github.sha }}.pdf
          asset_name: morello-early-performance-results-snapshot-${{ github.sha }}.pdf
          asset_content_type: application/pdf

  release:
    if: github.event_name == 'release' && github.event.action == 'created'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download book artifact
        uses: actions/download-artifact@v2
        with:
          name: book
          path: morello-early-performance-results-${{ github.event.release.tag_name }}

      - name: Download PDF artifact
        uses: actions/download-artifact@v2
        with:
          name: book.pdf
          path: morello-early-performance-results-${{ github.event.release.tag_name }}.pdf

      - name: Create archive
        run: zip -r morello-early-performance-results-${{ github.event.release.tag_name }}.zip morello-early-performance-results-${{ github.event.release.tag_name }}

      - name: Upload release book asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: morello-early-performance-results-${{ github.event.release.tag_name }}.zip
          asset_name: morello-early-performance-results-${{ github.event.release.tag_name }}.zip
          asset_content_type: application/zip

      - name: Upload release PDF asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: morello-early-performance-results-${{ github.event.release.tag_name }}.pdf
          asset_name: morello-early-performance-results-${{ github.event.release.tag_name }}.pdf
          asset_content_type: application/pdf

  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download book artifact
        uses: actions/download-artifact@v2
        with:
          name: book
          path: public

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
